package de.leistungsportal.mobile;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.webkit.*;import android.widget.*;import androidx.core.content.FileProvider;import java.io.File;
public class MainActivity extends Activity {
 private WebView web;private ValueCallback<Uri[]> fileCallback;private Uri cameraUri;
 @Override public void onCreate(Bundle state){super.onCreate(state);buildView();String url=getPreferences(0).getString("portal_url","");if(url.isEmpty())askUrl();else web.loadUrl(url);}
 private void buildView(){FrameLayout root=new FrameLayout(this);web=new WebView(this);root.addView(web,new FrameLayout.LayoutParams(-1,-1));Button settings=new Button(this);settings.setText("⚙");FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(64,64,Gravity.TOP|Gravity.END);p.setMargins(0,18,12,0);root.addView(settings,p);settings.setOnClickListener(v->askUrl());setContentView(root);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);CookieManager.getInstance().setAcceptCookie(true);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("http".equals(u.getScheme())||"https".equals(u.getScheme()))return false;startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}});web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView view,ValueCallback<Uri[]> cb,FileChooserParams params){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;openChooser();return true;}});}
 private void askUrl(){final EditText input=new EditText(this);input.setHint("https://portal.example.de/");input.setSingleLine(true);input.setText(getPreferences(0).getString("portal_url",""));input.setPadding(36,18,36,18);new AlertDialog.Builder(this).setTitle("Portaladresse").setMessage("HTTPS-Domain oder HTTP-Adresse im privaten VPN eingeben.").setView(input).setCancelable(!input.getText().toString().isEmpty()).setPositiveButton("Öffnen",(d,w)->{String u=input.getText().toString().trim();if(!u.matches("https?://.+")){Toast.makeText(this,"Adresse muss mit http:// oder https:// beginnen.",Toast.LENGTH_LONG).show();askUrl();return;}if(!u.endsWith("/"))u+="/";getPreferences(0).edit().putString("portal_url",u).apply();web.loadUrl(u);}).show();}
 private void openChooser(){try{File photo=File.createTempFile("portal_photo_",".jpg",getCacheDir());cameraUri=FileProvider.getUriForFile(this,getPackageName()+".files",photo);Intent camera=new Intent(MediaStore.ACTION_IMAGE_CAPTURE).putExtra(MediaStore.EXTRA_OUTPUT,cameraUri).addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);Intent files=new Intent(Intent.ACTION_GET_CONTENT).setType("image/*").putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);Intent chooser=Intent.createChooser(files,"Fotos auswählen");chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS,new Intent[]{camera});startActivityForResult(chooser,42);}catch(Exception e){fileCallback.onReceiveValue(null);fileCallback=null;Toast.makeText(this,"Kamera konnte nicht geöffnet werden.",Toast.LENGTH_LONG).show();}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=42||fileCallback==null)return;Uri[] out=null;if(result==RESULT_OK){if(data==null||data.getData()==null)out=new Uri[]{cameraUri};else if(data.getClipData()!=null){int n=data.getClipData().getItemCount();out=new Uri[n];for(int i=0;i<n;i++)out[i]=data.getClipData().getItemAt(i).getUri();}else out=new Uri[]{data.getData()};}fileCallback.onReceiveValue(out);fileCallback=null;cameraUri=null;}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}
